use super::{Corner, Corners, Edge, Edges, Move, OrientedCorner, OrientedEdge};
use phf::phf_map;

pub fn get_table_for(m: Move) -> (Edges, Corners) {
    let move_str = m.to_string();

    (EDGE_MOVE_TABLE[&*move_str], CORNER_MOVE_TABLE[&*move_str])
}

static EDGE_MOVE_TABLE: phf::Map<&'static str, Edges> = phf_map! {
    "NOP" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Rx1" => [OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::BR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::UR, o: 0}],
    "Rx2" => [OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::BR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::FR, o: 0}],
    "Rx3" => [OrientedEdge{e: Edge::BR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::DR, o: 0}],
    "Lx1" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Lx2" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Lx3" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Fx1" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::FL, o: 1}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::FR, o: 1},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::UF, o: 1}, OrientedEdge{e: Edge::DF, o: 1}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Fx2" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::DF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::UF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Fx3" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::FR, o: 1}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::FL, o: 1},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::DF, o: 1}, OrientedEdge{e: Edge::UF, o: 1}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Bx1" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::BR, o: 1}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::BL, o: 1}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::UB, o: 1}, OrientedEdge{e: Edge::DB, o: 1}],
    "Bx2" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}, OrientedEdge{e: Edge::BL, o: 0}],
    "Bx3" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::BL, o: 1}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::BR, o: 1}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::DB, o: 1}, OrientedEdge{e: Edge::UB, o: 1}],
    "Ux1" => [OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Ux2" => [OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Ux3" => [OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0},
              OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Dx1" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DF, o: 0}, OrientedEdge{e: Edge::DL, o: 0},
              OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Dx2" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::DB, o: 0},
              OrientedEdge{e: Edge::DR, o: 0}, OrientedEdge{e: Edge::DF, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
    "Dx3" => [OrientedEdge{e: Edge::UR, o: 0}, OrientedEdge{e: Edge::UF, o: 0}, OrientedEdge{e: Edge::UL, o: 0}, OrientedEdge{e: Edge::UB, o: 0}, OrientedEdge{e: Edge::DB, o: 0}, OrientedEdge{e: Edge::DR, o: 0},
              OrientedEdge{e: Edge::DF, o: 0}, OrientedEdge{e: Edge::DL, o: 0}, OrientedEdge{e: Edge::FR, o: 0}, OrientedEdge{e: Edge::FL, o: 0}, OrientedEdge{e: Edge::BL, o: 0}, OrientedEdge{e: Edge::BR, o: 0}],
};

static CORNER_MOVE_TABLE: phf::Map<&'static str, Corners> = phf_map! {
    "NOP" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Rx1" => [OrientedCorner{c: Corner::DFR, o: 1}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::URF, o: 2},
              OrientedCorner{c: Corner::DRB, o: 2}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::UBR, o: 1}],
    "Rx2" => [OrientedCorner{c: Corner::DRB, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::DFR, o: 0},
              OrientedCorner{c: Corner::UBR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::URF, o: 0}],
    "Rx3" => [OrientedCorner{c: Corner::UBR, o: 1}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::DRB, o: 2},
              OrientedCorner{c: Corner::URF, o: 2}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DFR, o: 1}],
    "Lx1" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::ULB, o: 2}, OrientedCorner{c: Corner::DBL, o: 1}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::UFL, o: 1}, OrientedCorner{c: Corner::DLF, o: 2}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Lx2" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Lx3" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::DLF, o: 2}, OrientedCorner{c: Corner::UFL, o: 1}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DBL, o: 1}, OrientedCorner{c: Corner::ULB, o: 2}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Fx1" => [OrientedCorner{c: Corner::UFL, o: 2}, OrientedCorner{c: Corner::DLF, o: 1}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::URF, o: 1}, OrientedCorner{c: Corner::DFR, o: 2}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Fx2" => [OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Fx3" => [OrientedCorner{c: Corner::DFR, o: 2}, OrientedCorner{c: Corner::URF, o: 1}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DLF, o: 1}, OrientedCorner{c: Corner::UFL, o: 2}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Bx1" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::UBR, o: 2}, OrientedCorner{c: Corner::DRB, o: 1},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::ULB, o: 1}, OrientedCorner{c: Corner::DBL, o: 2}],
    "Bx2" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}, OrientedCorner{c: Corner::DBL, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::UBR, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}],
    "Bx3" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::DBL, o: 2}, OrientedCorner{c: Corner::ULB, o: 1},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DRB, o: 1}, OrientedCorner{c: Corner::UBR, o: 2}],
    "Ux1" => [OrientedCorner{c: Corner::UBR, o: 0}, OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Ux2" => [OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0}, OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Ux3" => [OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0}, OrientedCorner{c: Corner::URF, o: 0},
              OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}],
    "Dx1" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}, OrientedCorner{c: Corner::DFR, o: 0}],
    "Dx2" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DBL, o: 0}, OrientedCorner{c: Corner::DRB, o: 0}, OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}],
    "Dx3" => [OrientedCorner{c: Corner::URF, o: 0}, OrientedCorner{c: Corner::UFL, o: 0}, OrientedCorner{c: Corner::ULB, o: 0}, OrientedCorner{c: Corner::UBR, o: 0},
              OrientedCorner{c: Corner::DRB, o: 0}, OrientedCorner{c: Corner::DFR, o: 0}, OrientedCorner{c: Corner::DLF, o: 0}, OrientedCorner{c: Corner::DBL, o: 0}],
};
